# .windriver-ci.yml, WR qemu gitlab CI configuration file.
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA


stages:
  - build-test

# Default job values
default:
  retry: 0
  interruptible: true
  image:
    name: registry.hub.docker.com/library/debian:11.7
    entrypoint: [""]

# Control when the pipeline is ran (on git push, for updates to merge request, etc)
workflow:
  rules:
    # Do not run for merge requests (will duplicate the push pipeline)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    # catchall to always run the pipeline if the above conditions fail
    - when: always

build-test-qemu-runtime:
  stage: build-test
  script:
    - apt-get update
    - apt-get upgrade -y && apt-get install -y autoconf automake bison bzip2 ca-certificates chrpath cmake curl
                diffstat flex g++ gawk gcc help2man lftp libelf1 libglib2.0-dev libpixman-1-dev
                libslirp-dev libx11-6 libxext6 libxpm4 libz-dev make ninja-build python3
                python3-pip screen texinfo unzip vsftpd wget git
    - pip3 install -U pip setuptools
    # build QEMU
    - ./configure
        --extra-cflags='-mno-avx512f'
        --extra-cxxflags='-mno-avx512f'
        --enable-strip
        --enable-slirp
        --disable-gio
        --disable-debug-info
        --disable-qom-cast-debug
    - make -j $(cat /proc/cpuinfo | grep "^processor" | wc -l)
    # run unit test
    - make check-unit
    # run block level test
    - make check-block
 
